import 'package:get/get.dart';
import 'package:bam_bam_vendor/app/pages/home_screen/screen/CityPreference/city_preference_screen.dart';
import 'package:bam_bam_vendor/app/pages/home_screen/screen/ringtone_settings_screen.dart';
import 'package:bam_bam_vendor/app/pages/home_screen/screen/profile/notifications_screen.dart';
import 'package:bam_bam_vendor/app/pages/home_screen/screen/profile/faq_screen.dart';
import 'package:bam_bam_vendor/app/pages/pages.dart';

part 'app_routes.dart';

class AppPages {
  static var transitionDuration = const Duration(milliseconds: 300);

  static const initial = _Paths.splashScreen;
  static final pages = <GetPage>[
    GetPage<SplashScreen>(
      name: _Paths.splashScreen,
      transitionDuration: transitionDuration,
      page: SplashScreen.new,
      binding: SplashBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<InAppUpdateScreen>(
      name: _Paths.inAppUpdateScreen,
      transitionDuration: transitionDuration,
      page: InAppUpdateScreen.new,
      binding: SplashBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<HomeScreen>(
      name: _Paths.homeScreen,
      transitionDuration: transitionDuration,
      page: HomeScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<LoginScreen>(
      name: _Paths.logainScreen,
      transitionDuration: transitionDuration,
      page: LoginScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<OtpScreen>(
      name: _Paths.otpScreen,
      transitionDuration: transitionDuration,
      page: OtpScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Registerstep1Screen>(
      name: _Paths.registerstep1Screen,
      transitionDuration: transitionDuration,
      page: Registerstep1Screen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Registerstep2Screen>(
      name: _Paths.registerstep2Screen,
      transitionDuration: transitionDuration,
      page: Registerstep2Screen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Registerstep3Screen>(
      name: _Paths.registerstep3Screen,
      transitionDuration: transitionDuration,
      page: Registerstep3Screen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),

    GetPage<ReviewingScreen>(
      name: _Paths.reviewingScreen,
      transitionDuration: transitionDuration,
      page: ReviewingScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BookingResponseScreen>(
      name: _Paths.bookingResponseScreen,
      transitionDuration: transitionDuration,
      page: BookingResponseScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<RideDetilesScreen>(
      name: _Paths.rideDetilesScreen,
      transitionDuration: transitionDuration,
      page: RideDetilesScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<DriverVehicalDetiles>(
      name: _Paths.driverVehicalDetiles,
      transitionDuration: transitionDuration,
      page: DriverVehicalDetiles.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Registerstep1Screen>(
      name: _Paths.registerScreen,
      transitionDuration: transitionDuration,
      page: Registerstep1Screen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<InRegister1>(
      name: _Paths.inRegister1,
      transitionDuration: transitionDuration,
      page: InRegister1.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<InRegister2>(
      name: _Paths.inRegister2,
      transitionDuration: transitionDuration,
      page: InRegister2.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<InRegister3>(
      name: _Paths.inRegister3,
      transitionDuration: transitionDuration,
      page: InRegister3.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<InRegister4>(
      name: _Paths.inRegister4,
      transitionDuration: transitionDuration,
      page: InRegister4.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AllocateVehicleScreen>(
      name: _Paths.allocateVehicleScreen,
      transitionDuration: transitionDuration,
      page: AllocateVehicleScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<DriverAllocateScreen>(
      name: _Paths.driverAllocateScreen,
      transitionDuration: transitionDuration,
      page: DriverAllocateScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<DriverHistoryScreen>(
      name: _Paths.driverHistoryScreen,
      transitionDuration: transitionDuration,
      page: DriverHistoryScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VehicleHistoryScreen>(
      name: _Paths.vehicleHistoryScreen,
      transitionDuration: transitionDuration,
      page: VehicleHistoryScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TripcancelScreen>(
      name: _Paths.tripcancelScreen,
      transitionDuration: transitionDuration,
      page: TripcancelScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TripcancellationPolicyScreen>(
      name: _Paths.tripcancellationPolicyScreen,
      transitionDuration: transitionDuration,
      page: TripcancellationPolicyScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TripdetilesScreen>(
      name: _Paths.tripdetilesScreen,
      transitionDuration: transitionDuration,
      page: TripdetilesScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TriplogoHomepage>(
      name: _Paths.triplogoHomepage,
      transitionDuration: transitionDuration,
      page: TriplogoHomepage.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<FineboardDetilesScreen>(
      name: _Paths.fineboardDetilesScreen,
      transitionDuration: transitionDuration,
      page: FineboardDetilesScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<RidereviewsDetilesscreen>(
      name: _Paths.ridereviewsDetilesscreen,
      transitionDuration: transitionDuration,
      page: RidereviewsDetilesscreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TransactionHistoryscreen>(
      transitionDuration: transitionDuration,
      name: _Paths.transactionHistoryscreen,
      page: TransactionHistoryscreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TopUpwalletscreen>(
      transitionDuration: transitionDuration,
      name: _Paths.topUpwalletscreen,
      page: TopUpwalletscreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<WithdrawScreen>(
      transitionDuration: transitionDuration,
      name: _Paths.withdrawScreen,
      page: WithdrawScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddTicketscreen>(
      transitionDuration: transitionDuration,
      name: _Paths.addTicketscreen,
      page: AddTicketscreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TicketDetilesscreen>(
      transitionDuration: transitionDuration,
      name: _Paths.ticketDetilesscreen,
      page: TicketDetilesscreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddNewdriversScreen>(
      transitionDuration: transitionDuration,
      name: _Paths.addNewdriversScreen,
      page: AddNewdriversScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<DriverHistorysScreen>(
      transitionDuration: transitionDuration,
      name: _Paths.driverHistorysScreen,
      page: DriverHistorysScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TripDetilesScreen>(
      transitionDuration: transitionDuration,
      name: _Paths.tripDetilesScreen,
      page: TripDetilesScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TripHistorysScreen>(
      transitionDuration: transitionDuration,
      name: _Paths.tripHistorysScreen,
      page: TripHistorysScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Addvehicale1Screen>(
      transitionDuration: transitionDuration,
      name: _Paths.addvehicale1Screen,
      page: Addvehicale1Screen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Addvehicale2Screen>(
      transitionDuration: transitionDuration,
      name: _Paths.addvehicale2Screen,
      page: Addvehicale2Screen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Addvehicale3Screen>(
      transitionDuration: transitionDuration,
      name: _Paths.addvehicale3Screen,
      page: Addvehicale3Screen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Addvehicale4Screen>(
      transitionDuration: transitionDuration,
      name: _Paths.addvehicale4Screen,
      page: Addvehicale4Screen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Addvehicale5Screen>(
      transitionDuration: transitionDuration,
      name: _Paths.addvehicale5Screen,
      page: Addvehicale5Screen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Addvehicale6Screen>(
      transitionDuration: transitionDuration,
      name: _Paths.addvehicale6Screen,
      page: Addvehicale6Screen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<Addvehicale7Screen>(
      transitionDuration: transitionDuration,
      name: _Paths.addvehicale7Screen,
      page: Addvehicale7Screen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ManagevehicleDetilesscreen>(
      transitionDuration: transitionDuration,
      name: _Paths.managevehicleDetilesscreen,
      page: ManagevehicleDetilesscreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ProfileHomescreen>(
      transitionDuration: transitionDuration,
      name: _Paths.profileHomescreen,
      page: ProfileHomescreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<CityPreferenceScreen>(
      transitionDuration: transitionDuration,
      name: _Paths.cityPreferenceScreen,
      page: CityPreferenceScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<RingtoneSettingsScreen>(
      transitionDuration: transitionDuration,
      name: _Paths.ringtoneSettingsScreen,
      page: RingtoneSettingsScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<NotificationsScreen>(
      transitionDuration: transitionDuration,
      name: _Paths.notificationsScreen,
      page: NotificationsScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<FaqScreen>(
      transitionDuration: transitionDuration,
      name: _Paths.faqScreen,
      page: FaqScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
  ];
}
